#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# AI Twin — Make FreeLLMAPI always-on
# ============================================================
# Sets up:
#   1. Wakelock so Android doesn't kill it when screen is off
#   2. Termux:Boot auto-start so it survives phone reboots
#   3. A tmux auto-restart wrapper so if it crashes, it comes back
# ============================================================

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

print_ok()   { echo -e "${GREEN}[OK]${NC} $1"; }
print_step() { echo -e "\n${CYAN}${BOLD}=== $1 ===${NC}"; }
print_warn() { echo -e "${YELLOW}[!]${NC} $1"; }
print_err()  { echo -e "${RED}[X]${NC} $1"; }

# 1. Wakelock
print_step "Acquiring wakelock"
if command -v termux-wake-lock &>/dev/null; then
    termux-wake-lock
    print_ok "Wakelock acquired (Android won't kill FreeLLMAPI when screen is off)"
else
    print_warn "termux-wake-lock not available. Install termux-api: pkg install termux-api"
fi

# 2. Create auto-restart wrapper
print_step "Creating auto-restart wrapper"
WRAPPER="$HOME/freellmapi-run.sh"
cat > "$WRAPPER" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Auto-restart wrapper for FreeLLMAPI
# If npm run dev exits for any reason, wait 5 seconds and start again
while true; do
    cd "$HOME/freellmapi"
    echo "[$(date)] Starting FreeLLMAPI..."
    npm run dev
    echo "[$(date)] FreeLLMAPI exited. Restarting in 5 seconds..."
    sleep 5
done
EOF
chmod +x "$WRAPPER"
print_ok "Created auto-restart wrapper at $WRAPPER"

# 3. Kill any old FreeLLMAPI tmux session and start fresh with the wrapper
print_step "Restarting FreeLLMAPI with auto-restart wrapper"
tmux kill-session -t freellmapi 2>/dev/null || true
sleep 1
tmux new-session -d -s freellmapi "$WRAPPER"
print_ok "FreeLLMAPI started in tmux session 'freellmapi' with auto-restart"

# 4. Termux:Boot auto-start
print_step "Setting up auto-start on phone reboot"
BOOT_DIR="$HOME/.termux/boot"
BOOT_SCRIPT="$BOOT_DIR/start-freellmapi.sh"

mkdir -p "$BOOT_DIR"

cat > "$BOOT_SCRIPT" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Auto-start FreeLLMAPI on phone boot
# Generated by ai-twin/freellmapi_always_on.sh

# Acquire wakelock so Android doesn't kill it
termux-wake-lock 2>/dev/null || true

# Wait for network to come up
sleep 10

# Start FreeLLMAPI in tmux with auto-restart wrapper
tmux new-session -d -s freellmapi "$HOME/freellmapi-run.sh"
EOF

chmod +x "$BOOT_SCRIPT"
print_ok "Auto-start script written to $BOOT_SCRIPT"

# 5. Check if Termux:Boot is installed
if [[ -d "$HOME/.termux/boot" ]]; then
    print_ok "Termux:Boot is installed — FreeLLMAPI will start on every reboot"
else
    print_warn "Termux:Boot app does not appear to be installed"
    print_warn "Without it, FreeLLMAPI won't auto-start after a phone reboot"
    print_warn "Install it from F-Droid: https://f-droid.org/packages/com.termux.boot/"
    print_warn "After installing, OPEN Termux:Boot once (just launch and close it)"
    print_warn "Then re-run this script"
fi

# 6. Verify
print_step "Verifying"
sleep 15
if curl -s -o /dev/null -w "%{http_code}" http://localhost:3001/v1/models 2>/dev/null | grep -q "200\|401\|403"; then
    print_ok "FreeLLMAPI is responding at http://localhost:3001/v1"
else
    print_warn "FreeLLMAPI still starting up. Check logs: tmux attach -t freellmapi"
fi

echo ""
echo "============================================"
echo "  FreeLLMAPI is now always-on."
echo "============================================"
echo ""
echo "What this means:"
echo "  - Survives screen-off (wakelock)"
echo "  - Survives crashes (auto-restart wrapper)"
echo "  - Survives phone reboots (Termux:Boot)"
echo ""
echo "Useful commands:"
echo "  View logs:        tmux attach -t freellmapi"
echo "  Detach logs:      Ctrl+B then D"
echo "  Stop FreeLLMAPI:  tmux kill-session -t freellmapi"
echo "  Start manually:   tmux new-session -d -s freellmapi ~/freellmapi-run.sh"
echo "  Dashboard:        termux-open-url http://localhost:5173"
echo ""
echo "If you ever want to update FreeLLMAPI:"
echo "  cd ~/freellmapi && git pull && npm install --no-audit --no-fund"
echo "  tmux kill-session -t freellmapi && tmux new-session -d -s freellmapi ~/freellmapi-run.sh"
