#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# AI Twin — hook_up.sh
# ============================================================
# One-stop integration script. Run this AFTER install.sh and after
# the twin is running. It wires up every integration that can be
# wired up without a human touching an external login screen.
#
# What this script DOES (automated):
#   1. Runs a full diagnostic on every tool + every API key
#   2. Sets up Termux:Boot auto-start (so twin survives reboot)
#   3. Optionally installs Node.js + n8n + ngrok (self-hosted automation)
#   4. Optionally configures SMTP (native email — no n8n needed)
#   5. Optionally saves webhook URLs (IFTTT / n8n / Make / custom)
#   6. Optionally sets up website monitoring for sites you care about
#   7. Generates a final health report at ~/ai-twin-memory/health_report.txt
#
# What this script CANNOT do (manual steps at the end):
#   - Install Termux:Boot app (you tap the F-Droid link)
#   - Grant Android battery exemption (you tap Settings → Apps → Termux)
#   - Create Gmail App Password (needs your Google 2FA login)
#   - Create ngrok account (needs your email signup)
#   - Authorize external OAuth (n8n → Gmail, n8n → Slack, etc.)
#
# Usage:
#   bash ~/ai-twin/hook_up.sh
# ============================================================

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
MAGENTA='\033[0;35m'
NC='\033[0m'

print_ok()   { echo -e "${GREEN}[✓]${NC} $1"; }
print_step() { echo -e "\n${CYAN}${BOLD}=== $1 ===${NC}"; }
print_warn() { echo -e "${YELLOW}[!]${NC} $1"; }
print_err()  { echo -e "${RED}[X]${NC} $1"; }
print_ask()  { echo -e "${MAGENTA}${BOLD}?${NC} $1"; }

# Memory dir
MEM_DIR="$HOME/ai-twin-memory"
mkdir -p "$MEM_DIR"

# Health report
REPORT="$MEM_DIR/health_report.txt"
echo "AI Twin Health Report — $(date)" > "$REPORT"
echo "============================================" >> "$REPORT"

# ------------------------------------------------------------
# 0. Find the ai-twin folder
# ------------------------------------------------------------
AI_TWIN_DIR="$HOME/ai-twin"
if [[ ! -d "$AI_TWIN_DIR" ]]; then
    print_err "ai-twin folder not found at $AI_TWIN_DIR"
    print_err "Install the twin first with: bash install.sh"
    exit 1
fi
cd "$AI_TWIN_DIR"

# Load .env if present
if [[ -f .env ]]; then
    set -a; source .env; set +a
fi

# ------------------------------------------------------------
# 1. Diagnostic — run all tool tests + API key checks
# ------------------------------------------------------------
print_step "Step 1: Full diagnostic"

print_ask "Run a full diagnostic of all 36 tools + all API keys? (Y/n) "
read -r RUN_DIAG
RUN_DIAG="${RUN_DIAG:-Y}"

if [[ "$RUN_DIAG" == "y" || "$RUN_DIAG" == "Y" ]]; then
    print_step "Running diagnostic (10-20 seconds)"
    if python diagnostic.py 2>&1 | tee -a "$REPORT"; then
        print_ok "Diagnostic complete — see $REPORT"
    else
        print_warn "Diagnostic had warnings — see $REPORT"
    fi
else
    print_ok "Skipping diagnostic"
    echo "Diagnostic skipped by user" >> "$REPORT"
fi

# ------------------------------------------------------------
# 2. Termux:Boot auto-start setup
# ------------------------------------------------------------
print_step "Step 2: Termux:Boot auto-start"

BOOT_DIR="$HOME/.termux/boot"
BOOT_SCRIPT="$BOOT_DIR/start-twin.sh"

if [[ -d "$HOME/.termux/boot" ]] || [[ -d "$HOME/.termux" ]]; then
    # Termux:Boot app appears to be installed (the .termux dir exists)
    mkdir -p "$BOOT_DIR"

    cat > "$BOOT_SCRIPT" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Auto-start the AI twin on phone boot
# Generated by hook_up.sh

# Acquire wakelock so Android doesn't kill us
termux-wake-lock 2>/dev/null || true

# Wait a few seconds for network to come up
sleep 5

# Start the twin in a tmux session
tmux new-session -d -s twin "cd $HOME/ai-twin && python twin_bot.py"
EOF
    chmod +x "$BOOT_SCRIPT"
    print_ok "Auto-start script written to $BOOT_SCRIPT"
    echo "Termux:Boot auto-start: CONFIGURED" >> "$REPORT"
else
    print_warn "Termux:Boot app does not appear to be installed"
    print_warn "Without it, the twin won't auto-start on phone reboot"
    print_warn "Install it from F-Droid: https://f-droid.org/packages/com.termux.boot/"
    echo "Termux:Boot auto-start: NOT INSTALLED (manual step needed)" >> "$REPORT"

    # Try to open F-Droid in browser
    print_ask "Open F-Droid to install Termux:Boot now? (y/N) "
    read -r OPEN_FDROID
    if [[ "$OPEN_FDROID" == "y" || "$OPEN_FDROID" == "Y" ]]; then
        termux-open-url "https://f-droid.org/packages/com.termux.boot/" 2>/dev/null \
            || xdg-open "https://f-droid.org/packages/com.termux.boot/" 2>/dev/null \
            || true
        print_warn "After installing Termux:Boot, OPEN IT ONCE (just launch and close it)"
        print_warn "Then re-run this script and it'll create the auto-start script."
    fi
fi

# ------------------------------------------------------------
# 3. SMTP / native email setup
# ------------------------------------------------------------
print_step "Step 3: Native email setup (SMTP)"

HAVE_SMTP=false
if [[ -n "$SMTP_HOST" ]] && [[ -n "$SMTP_USER" ]] && [[ -n "$SMTP_PASS" ]]; then
    print_ok "SMTP already configured: $SMTP_HOST as $SMTP_USER"
    HAVE_SMTP=true
    echo "SMTP: CONFIGURED ($SMTP_HOST)" >> "$REPORT"
else
    print_ask "Configure SMTP so the twin can send emails natively? (y/N) "
    read -r DO_SMTP
    if [[ "$DO_SMTP" == "y" || "$DO_SMTP" == "Y" ]]; then
        echo ""
        echo "Quick guide for Gmail (most common, free):"
        echo "  1. Go to https://myaccount.google.com/security"
        echo "  2. Enable 2-Step Verification (if not already on)"
        echo "  3. Go to https://myaccount.google.com/apppasswords"
        echo "  4. Create an App Password (16 chars, no spaces)"
        echo "  5. Paste it below when prompted"
        echo ""
        echo "Other providers: Outlook (smtp.office365.com:587),"
        echo "Yahoo (smtp.mail.yahoo.com:587), ProtonMail Bridge (127.0.0.1:1025)"
        echo ""

        read -p "SMTP host [smtp.gmail.com]: " IN_HOST
        read -p "SMTP port [587]: " IN_PORT
        read -p "SMTP user (your email): " IN_USER
        read -s -p "SMTP password (App Password, not your real password): " IN_PASS; echo
        read -p "From address (blank = same as user): " IN_FROM

        IN_HOST="${IN_HOST:-smtp.gmail.com}"
        IN_PORT="${IN_PORT:-587}"
        IN_FROM="${IN_FROM:-$IN_USER}"

        # Append to .env (preserving existing values)
        if [[ -f .env ]]; then
            # Check if SMTP vars already exist
            if grep -q "^SMTP_HOST=" .env; then
                # Replace existing
                sed -i "s|^SMTP_HOST=.*|SMTP_HOST=$IN_HOST|" .env
                sed -i "s|^SMTP_PORT=.*|SMTP_PORT=$IN_PORT|" .env
                sed -i "s|^SMTP_USER=.*|SMTP_USER=$IN_USER|" .env
                sed -i "s|^SMTP_PASS=.*|SMTP_PASS=$IN_PASS|" .env
                sed -i "s|^SMTP_FROM=.*|SMTP_FROM=$IN_FROM|" .env
            else
                # Append
                cat >> .env <<EOF

# Native email automation (added by hook_up.sh)
SMTP_HOST=$IN_HOST
SMTP_PORT=$IN_PORT
SMTP_USER=$IN_USER
SMTP_PASS=$IN_PASS
SMTP_FROM=$IN_FROM
EOF
            fi
        else
            print_err ".env not found — cannot configure SMTP"
            echo "SMTP: FAILED (.env missing)" >> "$REPORT"
        fi

        # Reload env
        set -a; source .env; set +a

        # Test send
        print_step "Sending test email"
        python -c "
import os, sys
sys.path.insert(0, '.')
from tools import tool_send_email
to = '$IN_USER'
print(tool_send_email(to=to, subject='AI Twin test email', body='If you can read this, your twin can send emails natively. No n8n needed.'))
" 2>&1 | tee -a "$REPORT"

        if [[ ${PIPESTATUS[0]} -eq 0 ]]; then
            print_ok "SMTP configured. Check your inbox at $IN_USER"
            echo "SMTP: CONFIGURED ($IN_HOST)" >> "$REPORT"
            HAVE_SMTP=true
        else
            print_warn "SMTP test failed — credentials may be wrong"
            echo "SMTP: TEST FAILED" >> "$REPORT"
        fi
    else
        echo "SMTP: SKIPPED by user" >> "$REPORT"
    fi
fi

# ------------------------------------------------------------
# 4. n8n self-hosting (optional, advanced)
# ------------------------------------------------------------
print_step "Step 4: n8n self-hosting (optional)"

print_ask "Install n8n + ngrok for self-hosted automation? (y/N) "
read -r DO_N8N

if [[ "$DO_N8N" == "y" || "$DO_N8N" == "Y" ]]; then
    print_step "Installing Node.js + n8n + ngrok (5-10 minutes)"

    # Node.js
    pkg install -y nodejs-lts >/dev/null 2>&1 || pkg install -y nodejs >/dev/null 2>&1 || true
    if command -v node &>/dev/null; then
        print_ok "Node.js: $(node --version)"
        echo "Node.js: $(node --version)" >> "$REPORT"
    else
        print_err "Node.js install failed"
        echo "n8n: FAILED (no Node.js)" >> "$REPORT"
    fi

    # n8n
    if command -v node &>/dev/null; then
        print_step "Installing n8n (3-5 minutes)"
        npm install -g n8n >/dev/null 2>&1 || true
        if command -v n8n &>/dev/null; then
            print_ok "n8n: $(n8n --version)"
            echo "n8n: $(n8n --version)" >> "$REPORT"
        else
            print_err "n8n install failed — see N8N_SELFHOST_GUIDE.md"
            echo "n8n: FAILED" >> "$REPORT"
        fi
    fi

    # ngrok
    NGROK_BIN="$PREFIX/bin/ngrok"
    if [[ ! -x "$NGROK_BIN" ]]; then
        print_step "Installing ngrok"
        curl -sL -o /tmp/ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm64.zip 2>/dev/null
        if [[ -f /tmp/ngrok.zip ]]; then
            unzip -o /tmp/ngrok.zip -d /tmp/ >/dev/null 2>&1
            mv /tmp/ngrok "$NGROK_BIN" 2>/dev/null && chmod +x "$NGROK_BIN"
            rm -f /tmp/ngrok.zip
            print_ok "ngrok installed"
            echo "ngrok: INSTALLED" >> "$REPORT"
        else
            print_err "ngrok download failed"
            echo "ngrok: FAILED" >> "$REPORT"
        fi
    else
        print_ok "ngrok already installed"
        echo "ngrok: ALREADY INSTALLED" >> "$REPORT"
    fi

    # n8n config
    mkdir -p "$HOME/.n8n"
    if [[ ! -f "$HOME/.n8n/.env" ]]; then
        cat > "$HOME/.n8n/.env" <<'N8NENV'
N8N_HOST=localhost
N8N_PORT=5678
N8N_PROTOCOL=http
N8N_DIAGNOSTICS_ENABLED=false
N8N_PERSONALIZATION_ENABLED=false
N8N_BASIC_AUTH_ACTIVE=true
N8N_BASIC_AUTH_USER=admin
N8N_BASIC_AUTH_PASSWORD=change-this-password
N8NENV
        print_ok "n8n config created at ~/.n8n/.env"
        print_warn "CHANGE THE PASSWORD in ~/.n8n/.env before first run"
    fi

    # ngrok authtoken
    if command -v ngrok &>/dev/null; then
        if ! ngrok config check 2>/dev/null | grep -q "authtoken"; then
            echo ""
            print_ask "Paste your ngrok authtoken (from https://dashboard.ngrok.com/get-started/your-authtoken), or press Enter to skip: "
            read -r NGROK_TOKEN
            if [[ -n "$NGROK_TOKEN" ]]; then
                ngrok config add-authtoken "$NGROK_TOKEN" 2>/dev/null
                print_ok "ngrok authtoken saved"
                echo "ngrok authtoken: CONFIGURED" >> "$REPORT"
            else
                print_warn "Skipped — set it later with: ngrok config add-authtoken YOUR_TOKEN"
                echo "ngrok authtoken: SKIPPED" >> "$REPORT"
            fi
        else
            print_ok "ngrok authtoken already set"
            echo "ngrok authtoken: ALREADY SET" >> "$REPORT"
        fi
    fi

    # Start n8n + ngrok if both ready
    if command -v n8n &>/dev/null && command -v ngrok &>/dev/null; then
        print_step "Starting n8n + ngrok in tmux sessions"
        if ! tmux has-session -t n8n 2>/dev/null; then
            tmux new-session -d -s n8n 'n8n start'
            print_ok "n8n started in tmux session 'n8n'"
        else
            print_ok "n8n already running"
        fi
        sleep 5
        if ! tmux has-session -t ngrok 2>/dev/null; then
            tmux new-session -d -s ngrok 'ngrok http 5678'
            print_ok "ngrok started in tmux session 'ngrok'"
        else
            print_ok "ngrok already running"
        fi
        sleep 3

        # Get public URL
        NGROK_URL=$(curl -s http://localhost:4040/api/tunnels 2>/dev/null | python -c "import sys,json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])" 2>/dev/null || echo "")
        if [[ -n "$NGROK_URL" ]]; then
            print_ok "n8n public URL: $NGROK_URL"
            echo "n8n public URL: $NGROK_URL" >> "$REPORT"
            echo ""
            echo -e "${GREEN}Open n8n editor at:${NC} $NGROK_URL"
            echo -e "${GREEN}Or locally at:${NC}    http://localhost:5678"
        else
            print_warn "Could not get ngrok URL yet — wait 30s and run:"
            print_warn "  curl -s http://localhost:4040/api/tunnels | python -m json.tool"
        fi
    fi
else
    echo "n8n: SKIPPED by user (twin has native email/calendar/RSS instead)" >> "$REPORT"
fi

# ------------------------------------------------------------
# 5. Save webhook URLs (IFTTT / Make / custom)
# ------------------------------------------------------------
print_step "Step 5: Save webhook URLs"

print_ask "Do you have any webhook URLs to save (IFTTT, Make, Zapier, custom)? (y/N) "
read -r DO_WEBHOOKS

while [[ "$DO_WEBHOOKS" == "y" || "$DO_WEBHOOKS" == "Y" ]]; do
    read -p "Webhook name (e.g., 'ifttt_email', 'make_slack'): " WH_NAME
    read -p "Webhook URL: " WH_URL
    read -p "Description (optional): " WH_DESC

    if [[ -n "$WH_NAME" ]] && [[ -n "$WH_URL" ]]; then
        python -c "
import sys; sys.path.insert(0, '.')
from tools import tool_save_webhook
print(tool_save_webhook(name='$WH_NAME', webhook_url='$WH_URL', description='''$WH_DESC'''))
" 2>&1 | tee -a "$REPORT"
        print_ok "Saved webhook '$WH_NAME'"
        echo "Webhook saved: $WH_NAME -> $WH_URL" >> "$REPORT"
    else
        print_warn "Need both name and URL"
    fi

    print_ask "Save another webhook? (y/N) "
    read -r DO_WEBHOOKS
done

# ------------------------------------------------------------
# 6. Website monitoring
# ------------------------------------------------------------
print_step "Step 6: Website monitoring setup"

print_ask "Set up website change monitoring? (y/N) "
read -r DO_MONITOR

while [[ "$DO_MONITOR" == "y" || "$DO_MONITOR" == "Y" ]]; do
    read -p "Website URL to monitor (e.g., https://example.com): " MON_URL
    read -p "What to watch for (e.g., 'price drop', 'new post', 'any change') [any change]: " MON_WATCH
    MON_WATCH="${MON_WATCH:-any change}"

    if [[ -n "$MON_URL" ]]; then
        python -c "
import sys; sys.path.insert(0, '.')
from tools import tool_monitor_website
print(tool_monitor_website(url='$MON_URL', watch_for='''$MON_WATCH'''))
" 2>&1 | tee -a "$REPORT"
        print_ok "Monitoring $MON_URL"
        echo "Monitoring: $MON_URL (watching for: $MON_WATCH)" >> "$REPORT"
    else
        print_warn "URL is required"
    fi

    print_ask "Monitor another site? (y/N) "
    read -r DO_MONITOR
done

# ------------------------------------------------------------
# 7. RSS feeds
# ------------------------------------------------------------
print_step "Step 7: RSS feed subscriptions"

print_ask "Add RSS feeds for the twin to monitor? (y/N) "
read -r DO_RSS

while [[ "$DO_RSS" == "y" || "$DO_RSS" == "Y" ]]; do
    read -p "RSS/Atom feed URL (e.g., https://hnrss.org/frontpage): " RSS_URL
    if [[ -n "$RSS_URL" ]]; then
        # Test fetch
        python -c "
import sys; sys.path.insert(0, '.')
from tools import tool_read_rss
print(tool_read_rss(url='$RSS_URL', limit=2))
" 2>&1 | head -20 | tee -a "$REPORT"
        # Save to feeds file (the twin reads this on startup)
        FEEDS_FILE="$MEM_DIR/rss_feeds.txt"
        if ! grep -q "^$RSS_URL$" "$FEEDS_FILE" 2>/dev/null; then
            echo "$RSS_URL" >> "$FEEDS_FILE"
            print_ok "Subscribed to $RSS_URL"
            echo "RSS feed added: $RSS_URL" >> "$REPORT"
        else
            print_warn "Already subscribed to $RSS_URL"
        fi
    fi
    print_ask "Add another feed? (y/N) "
    read -r DO_RSS
done

# ------------------------------------------------------------
# 8. Final health report
# ------------------------------------------------------------
print_step "Step 8: Final report"

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Integration setup complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Full health report saved to:"
echo "  $REPORT"
echo ""
echo "============================================"
echo "MANUAL STEPS YOU STILL NEED TO DO:"
echo "============================================"
echo ""
echo -e "${YELLOW}1. Termux:Boot app${NC}"
echo "   If not installed, get it from F-Droid:"
echo "   https://f-droid.org/packages/com.termux.boot/"
echo "   After installing, OPEN IT ONCE (just launch and close)"
echo ""
echo -e "${YELLOW}2. Android battery exemption${NC}"
echo "   Settings → Apps → Termux → Battery → Unrestricted"
echo "   Without this, Android will kill the twin when screen is off"
echo ""
echo -e "${YELLOW}3. Test your twin${NC}"
echo "   Open Telegram, find your bot, send:"
echo "     /help       (see all commands)"
echo "     what time is it?"
echo "     search the web for AI news"
echo "     send me an email (if SMTP configured)"
echo "     what's new on Hacker News? (tests RSS)"
echo ""
echo "============================================"
echo "USEFUL COMMANDS:"
echo "============================================"
echo -e "  ${CYAN}twin-start${NC}   start the bot"
echo -e "  ${CYAN}twin-logs${NC}    view live logs"
echo -e "  ${CYAN}twin-stop${NC}    stop the bot"
echo -e "  ${CYAN}twin-status${NC}  check if running"
echo ""
if command -v n8n &>/dev/null; then
echo "  n8n editor:  http://localhost:5678"
echo "  n8n logs:    tmux attach -t n8n"
echo "  ngrok URL:   curl -s http://localhost:4040/api/tunnels"
fi
echo ""
echo "Re-run this script any time to add more integrations:"
echo -e "  ${CYAN}bash ~/ai-twin/hook_up.sh${NC}"
